# Created automatically by Cursor AI (2024-12-19)
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm run install:all
      
      - name: Lint frontend
        run: npm run lint:frontend
      
      - name: Lint gateway
        run: npm run lint:gateway
      
      - name: Lint SDK
        run: npm run lint:sdk
      
      - name: Type check frontend
        run: cd apps/frontend && npm run type-check
      
      - name: Type check gateway
        run: cd apps/gateway && npm run build

  test:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Node dependencies
        run: npm run install:all
      
      - name: Install Python dependencies
        run: |
          cd apps/orchestrator && pip install -r requirements.txt
          cd ../../apps/workers && pip install -r requirements.txt
      
      - name: Run frontend tests
        run: npm run test:frontend
      
      - name: Run gateway tests
        run: npm run test:gateway
      
      - name: Run SDK tests
        run: npm run test:sdk

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm run install:all
      
      - name: Build SDK
        run: npm run build:sdk
      
      - name: Build frontend
        run: npm run build:frontend
      
      - name: Build gateway
        run: npm run build:gateway
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            apps/frontend/.next
            apps/gateway/dist
            packages/sdk/dist

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
